const IMG='https://images.unsplash.com/';
const P={
 hero:IMG+'photo-1494774157365-9e04c6720e47?auto=format&fit=crop&w=1800&q=88',
 travel:IMG+'photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=88',
 dog:IMG+'photo-1552053831-71594a27632d?auto=format&fit=crop&w=1400&q=88',
 work:IMG+'photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=88',
 couple:IMG+'photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1600&q=88',
 soft:IMG+'photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1600&q=88'
};
const app=document.getElementById('app'),music=document.getElementById('bgMusic');
music.volume=0.52;
let state=JSON.parse(localStorage.getItem('nainaQuestV5')||'null')||{stage:0,quiz:0,memory:0,cards:[],secret:false};
const save=()=>localStorage.setItem('nainaQuestV5',JSON.stringify(state));
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)}
function setChapter(t){document.getElementById('chapterLabel').textContent=t}
function screen(html,cls=''){app.innerHTML=`<section class="screen ${cls}"><div class="shell">${html}</div></section>`;window.scrollTo({top:0,behavior:'smooth'})}
function home(){setChapter('A little world');screen(`<div class="hero-grid"><div class="hero-copy"><div class="kicker"><span>07</span><i>•</i><span>10</span><i>•</i><span>1994</span></div><h1>Naina,<br><em>this little world<br>is yours.</em></h1><p class="lead">A birthday message felt too small.<br>So I made you a place to wander through instead.</p><button class="primary" onclick="start()">Begin the story <b>↗</b></button><p class="micro">made slowly • with a ridiculous amount of thought</p></div><div class="hero-art"><img src="${P.hero}" alt="soft romantic landscape"><div class="art-note"><span>for</span><strong>Naina</strong><small>one day • one story • one very cute human</small></div><div class="orb orb1"></div><div class="orb orb2"></div></div></div>`)}
function start(){setChapter('Before we begin');screen(`<div class="auth-card"><div class="step">01 / 02</div><div class="mini-heart">♡</div><h2>First, tell me<br><em>who you are.</em></h2><p>I made this for exactly one person.</p><input id="name" class="input" placeholder="Type your name" autocomplete="off" onkeydown="if(event.key==='Enter')checkName()"><button class="primary wide" onclick="checkName()">Continue <b>→</b></button><span class="hint">There is no trick. Probably. 😌</span></div>`);setTimeout(()=>playSong(true),80)}
function checkName(){const n=document.getElementById('name').value.trim().toLowerCase();if(n==='naina'){setChapter('One tiny lock');screen(`<div class="auth-card"><div class="step">02 / 02</div><div class="mini-heart">♡</div><h2>One little question<br><em>before the magic.</em></h2><p>Someone born on <strong>05 September 1994</strong> made this.<br>When is their birthday?</p><div class="date-wrap"><input id="code" class="input date-input" type="date" aria-label="Creator birthday" max="2026-12-31"></div><button class="primary wide" onclick="unlock()">Unlock my birthday <b>→</b></button><span class="hint">Pick the date from the calendar. ❤️</span></div>`)}else toast('This world is looking for Naina. ❤️')}
function unlock(){const v=document.getElementById('code')?.value;if(v==='1994-09-05'){state.stage=1;save();welcome()}else toast('Almost… think of the person who made this. 😌')}
function welcome(){setChapter('Access granted');screen(`<div class="welcome"><span class="eyebrow">access granted</span><h2>Hi, Naina.</h2><p>There are little pieces of you hidden throughout this place —<br>the things you love, the things you dream about, and a few things I notice.</p><div class="rule"></div><p class="quote">“Take your time. The point isn't to finish.<br>The point is to notice.”</p><button class="primary" onclick="quiz()">Let’s see what I know <b>→</b></button></div>`)}
const quizData=[
 ['A good day for you probably needs…',['a quiet room','a dog nearby 🐾','a spreadsheet'],1,'I had a feeling you’d pick that. 🐾'],
 ['If a map suddenly appeared, your first thought would be…',['Where are we going? ✈️','How much is the GST?','Can we cancel?'],0,'Exactly. Somewhere new sounds better already.'],
 ['The dream you are quietly building is…',['Business Analyst era 📊','Professional napper','CEO of snacks'],0,'And I hope you become ridiculously good at it.'],
 ['What makes this birthday little world different?',['It has code','It has feelings','It has Excel formulas'],1,'Correct. The code was easy. The feelings took longer. ❤️'],
 ['Last one. Who is this entire thing really about?',['Naina','Definitely Naina','All answers are Naina ❤️'],2,'There was never really another answer.']
];
function progress(n){return `<div class="progressline"><span>${String(state.quiz+1).padStart(2,'0')}</span><div><i style="width:${((state.quiz)/n)*100}%"></i></div><span>${String(n).padStart(2,'0')}</span></div>`}
function quiz(){setChapter('Chapter 01 · The little test');if(state.quiz>=quizData.length){memories();return}const q=quizData[state.quiz];screen(`<div class="chapter-head">${progress(quizData.length)}<span class="eyebrow">chapter one</span><h2>Let’s see if I<br><em>know you.</em></h2><p>There are no wrong answers. Just very revealing ones.</p></div><div class="question-card"><div class="q-number">0${state.quiz+1}</div><h3>${q[0]}</h3><div class="answer-list">${q[1].map((x,i)=>`<button onclick="answer(${i})"><span>${String.fromCharCode(65+i)}</span>${x}<b>↗</b></button>`).join('')}</div><div id="quizNote" class="feedback"></div></div>`)}
function answer(i){const q=quizData[state.quiz];const note=document.getElementById('quizNote');if(i===q[2]){note.textContent=q[3];note.className='feedback good';document.querySelectorAll('.answer-list button').forEach(b=>b.disabled=true);state.quiz++;save();setTimeout(quiz,800)}else{note.textContent='Hmm. I’ll let you think about that one again. 😏';note.className='feedback';}}
const memoryData=[
 {word:'BEGINNINGS',eyebrow:'before all the stories',img:'assets/memory-1.jpg',title:'The little girl before the world got to know her',text:'Before the travels, the dreams, the crazy pictures and all the stories… there was this little face. Some people grow up and become completely different. Some simply grow into the person they were always meant to be.'},
 {word:'PAWS',eyebrow:'the soft spot',img:'assets/memory-2.jpg',title:'You + a dog = instant happiness',text:'I think your love for dogs says something lovely about you. You have a very soft corner for creatures who give affection without asking for anything back. And honestly, this picture makes that impossible to hide. 🐾'},
 {word:'ENERGY',eyebrow:'the version that just goes for it',img:'assets/memory-3.jpg',title:'There is always a little more life in you',text:'You have this side that does not need everything to be perfectly planned before having fun. Sometimes you just step into the moment, dance, laugh and let the night happen.'},
 {word:'CUTE',eyebrow:'the unfair advantage',img:'assets/memory-4.jpg',title:'This one needs no explanation',text:'Some photographs are beautiful because everything is perfectly arranged. This one is beautiful because you look completely, ridiculously, naturally cute without even trying. Very unfair, honestly. 😂❤️'},
 {word:'SOFT',eyebrow:'the quiet moments',img:'assets/memory-5.jpg',title:'Some moments don’t need words',text:'There are photographs where nothing dramatic is happening, and somehow they stay with you longer. Maybe because they feel honest. Maybe because they feel like you.'},
 {word:'US',eyebrow:'the people beside us',img:'assets/memory-6.jpg',title:'The people who become part of the story',text:'Life is not only made of big milestones. A huge part of it is tiny frames with people who know you, love you, tease you and somehow make ordinary days memorable.'},
 {word:'PLAY',eyebrow:'the fun you carry',img:'assets/memory-7.jpg',title:'Never lose this version of yourself',text:'The grown-up version of you can chase goals, become a brilliant Business Analyst and build a beautiful life. But I hope she always keeps this playful, slightly crazy version too.'},
 {word:'GLOW',eyebrow:'look at you now',img:'assets/memory-8.jpg',title:'And then there is the woman you are becoming',text:'From that tiny childhood photograph to this — the story keeps moving. You have so many chapters ahead, and somehow I already know they are going to be interesting.'}
];
function memories(){setChapter('Chapter 02 · Your little gallery');screen(`<div class="chapter-head wide-head"><span class="eyebrow">chapter two</span><h2>A few pieces of<br><em>your story.</em></h2><p>I brought back the photo unlocks. ❤️<br>Open them in order — each picture has a little thought waiting behind it.</p></div><div class="memory-progress"><div><span id="memoryCount">${Math.min(state.memory,memoryData.length)} / ${memoryData.length}</span><small>memories discovered</small></div><div class="memory-track"><i id="memoryTrack" style="width:${(Math.min(state.memory,memoryData.length)/memoryData.length)*100}%"></i></div></div><div class="photo-grid">${memoryData.map((m,i)=>`<button class="photo-card ${i<state.memory?'unlocked':''} ${i>state.memory?'locked':''}" onclick="openNotice(${i})"><span class="photo-index">0${i+1}</span><img src="${m.img}" alt="${m.word}" loading="lazy"><span class="photo-shade"></span>${i>state.memory?'<span class="photo-lock">♡</span>':''}<span class="photo-meta"><strong>${i<state.memory?m.word:'LOCKED'}</strong><small>${i<state.memory?m.eyebrow:'open the previous memory first'}</small></span>${i<state.memory?'<span class="photo-check">✓</span>':''}</button>`).join('')}</div><div class="chapter-foot"><span id="memoryMessage">${state.memory>=memoryData.length?'All the little pieces are open. ❤️':'Start with the first photograph.'}</span><button id="memoryNext" class="primary ${state.memory<memoryData.length?'disabled':''}" onclick="afterNotices()">Continue the story <b>→</b></button></div>`)}
function refreshMemoryCards(){document.querySelectorAll('.photo-card').forEach((card,i)=>{const unlocked=i<state.memory;card.classList.toggle('unlocked',unlocked);card.classList.toggle('locked',i>state.memory);const strong=card.querySelector('.photo-meta strong');const small=card.querySelector('.photo-meta small');if(strong)strong.textContent=unlocked?memoryData[i].word:'LOCKED';if(small)small.textContent=unlocked?memoryData[i].eyebrow:'click the previous memory first';const lock=card.querySelector('.photo-lock');if(lock)lock.style.display=i>state.memory?'grid':'none';const check=card.querySelector('.photo-check');if(check)check.style.display=unlocked?'grid':'none'});const count=document.getElementById('memoryCount');if(count)count.textContent=`${Math.min(state.memory,memoryData.length)} / ${memoryData.length}`;const track=document.getElementById('memoryTrack');if(track)track.style.width=`${(Math.min(state.memory,memoryData.length)/memoryData.length)*100}%`;const msg=document.getElementById('memoryMessage');if(msg)msg.textContent=state.memory>=memoryData.length?'All the little pieces are open. ❤️':'The next memory just unlocked. ✨';const next=document.getElementById('memoryNext');if(next&&state.memory>=memoryData.length)next.classList.remove('disabled')}
function openNotice(i){if(i>state.memory){toast('That memory is still waiting for its turn. ❤️');return}const m=memoryData[i];const modal=document.createElement('div');modal.className='overlay';modal.innerHTML=`<div class="photo-modal"><button class="close photo-close" aria-label="Close photo" onclick="this.closest('.overlay').remove()">×</button><div class="photo-modal-image"><img src="${m.img}" alt="${m.title}"><span class="modal-number">0${i+1} / ${memoryData.length}</span><span class="modal-tag">${m.eyebrow}</span></div><div class="modal-copy"><div class="modal-word">${m.word}</div><h3>${m.title}</h3><p>${m.text}</p><span class="slow">some memories are better looked at twice.</span></div></div>`;document.body.appendChild(modal);if(i===state.memory){state.memory++;save();refreshMemoryCards()}else{refreshMemoryCards()}setTimeout(()=>{const close=modal.querySelector('.close');close?.focus()},50)}
function afterNotices(){if(state.memory<memoryData.length){toast('There are still a few thoughts waiting. ❤️');return}puzzle()}
function puzzle(){setChapter('Chapter 03 · Find it');state.stage=3;save();screen(`<div class="chapter-head"><span class="eyebrow">chapter three</span><h2>A little game<br><em>for the curious.</em></h2><p>There is one tiny heart hiding in this picture.<br>Find it. Don’t overthink it.</p></div><div class="hunt"><img src="assets/memory-2.jpg" alt="Naina with a dog"><button class="hidden-heart" aria-label="Find the heart" onclick="foundHeart()">♡</button><div class="hunt-tip">look closely <span>⌁</span></div></div><div class="centerline" id="huntStatus">You’ll know when you find it. 👀</div>`)}
function foundHeart(){document.querySelector('.hidden-heart')?.classList.add('found');document.getElementById('huntStatus').textContent='There it is. You always notice the little things. ❤️';setTimeout(song,900)}
function song(){setChapter('Chapter 04 · The little things');state.stage=4;save();screen(`<div class="little-things"><div class="chapter-head wide-head"><span class="eyebrow">chapter four</span><h2>The things that make<br><em>you, you.</em></h2><p>The soundtrack is already playing in the background. So instead of asking you to press play again, I wanted to pause here for three things I genuinely love about the person this little world was made for.</p></div><div class="things-grid"><article class="thing-card"><span class="thing-no">01</span><div class="thing-icon">🐾</div><h3>That soft spot</h3><p>You can spot a dog and suddenly the rest of the world becomes a little less important. I hope you never lose that softness.</p></article><article class="thing-card"><span class="thing-no">02</span><div class="thing-icon">✈</div><h3>That wanderlust</h3><p>There are still places we haven't seen, roads we haven't taken and random plans we haven't made yet. I like that thought.</p></article><article class="thing-card"><span class="thing-no">03</span><div class="thing-icon">⌁</div><h3>That ambition</h3><p>Future Business Analyst Naina sounds pretty good. I hope you build the career, life and confidence you keep dreaming about.</p></article></div><div class="little-things-foot"><span>And yes… the music is still playing. ❤️</span><button class="primary" onclick="cards()">Keep going <b>→</b></button></div></div>`)}
function playSong(fromStart=false){if(fromStart&&music.currentTime===0)music.currentTime=0;music.play().then(()=>{const status=document.getElementById('songStatus');if(status)status.textContent='Now playing… stay a little longer. ❤️';document.getElementById('musicBtn').classList.add('playing');document.querySelector('#musicBtn span').textContent='Playing'}).catch(()=>{const status=document.getElementById('songStatus');if(status)status.textContent='Tap Music once to start the soundtrack. ❤️'})}
const cardData=[
 ['SOFTNESS','You have a way of caring that doesn’t need an announcement. Maybe that quiet kind of softness is one of the nicest things about you.'],
 ['PAWS','Maybe you love dogs because they understand something simple: love doesn’t always need words. It just needs to be there.'],
 ['WANDER','I hope you never stop wanting to see what is around the next corner. There are too many roads left to take.'],
 ['AMBITION','One day, I hope you look back at the version of you who was still figuring it out — and feel proud that she kept going.'],
 ['CUTE','There are sophisticated words for many things. For this one, I only have: ridiculously, unfairly, impossibly cute. 😂❤️'],
 ['MOMENTS','We almost never realise we are inside a memory while it is happening. That’s why I want to notice more of them.'],
 ['SOMEDAY','There are places I want to see, conversations I want to have and random plans I want to make. Some would be better with you there.'],
 ['YOU','Out of everything I could write here, this is the one word that somehow says the most.']
];
function cards(){setChapter('Chapter 05 · Read slowly');state.stage=5;save();screen(`<div class="chapter-head wide-head"><span class="eyebrow">chapter five</span><h2>Things I never<br><em>said out loud.</em></h2><p>Each card starts with one word.<br>Turn it over and read the thought behind it — slowly.</p></div><div class="quote-grid">${cardData.map((c,i)=>`<button class="quote-card ${state.cards.includes(i)?'open':''}" aria-label="Open ${c[0]} card" onclick="flipCard(this,${i})"><span class="quote-inner"><span class="quote-face quote-front"><span class="quote-top"><small>THOUGHT 0${i+1}</small><i>♡</i></span><strong>${c[0]}</strong><span class="quote-divider"></span><em>turn me over <b>↗</b></em></span><span class="quote-face quote-back"><span class="quote-top"><small>${c[0]}</small><i>✦</i></span><h3>${c[0]}</h3><p>${c[1]}</p><em>turn back <b>↻</b></em></span></span></button>`).join('')}</div><div class="chapter-foot"><span id="cardCount">${state.cards.length} / ${cardData.length} opened</span><button id="cardNext" class="primary ${state.cards.length===cardData.length?'':'disabled'}" onclick="secret()">There’s one last lock <b>→</b></button></div>`)}
function flipCard(el,i){el.classList.toggle('open');if(el.classList.contains('open')&&!state.cards.includes(i)){state.cards.push(i);save();const c=document.getElementById('cardCount');c.textContent=`${state.cards.length} / ${cardData.length} opened`;if(state.cards.length===cardData.length)document.getElementById('cardNext').classList.remove('disabled')}}
function secret(){if(state.cards.length<cardData.length){toast('Open every card. The last one is waiting. ❤️');return}setChapter('Chapter 06 · One last lock');state.stage=6;save();screen(`<div class="secret-layout"><div class="secret-symbol">07<br><span>10</span></div><div><span class="eyebrow">chapter six</span><h2>One final little<br><em>secret.</em></h2><p>The date that belongs to this whole story.<br>Pick Naina’s birthday from the calendar.</p><input id="secret" class="input secret-input date-input" type="date" aria-label="Naina birthday" min="1990-01-01" max="2026-12-31"><button class="primary" onclick="checkSecret()">Unlock the last chapter <b>→</b></button><div id="secretHint" class="hint">You’ve seen this date before. 😉</div></div></div>`)}
function checkSecret(){if(document.getElementById('secret')?.value==='1994-10-07'){state.secret=true;save();finalQuestion()}else{document.getElementById('secretHint').textContent='Nope. Pick the birthday you already know. ❤️'}}
function finalQuestion(){setChapter('Chapter 07 · The question');screen(`<div class="final-q"><span class="eyebrow">chapter seven</span><div class="big-quote">“</div><h2>So… one more adventure?<br><em>With me?</em></h2><p>I already know what I hope you choose.<br>But I thought you should get the illusion of a choice. 😌</p><div class="choice-zone"><button class="yes" onclick="celebrate()">YES, obviously ❤️</button><button id="noBtn" class="no" type="button">NO 🙈</button></div><div id="noHint" class="no-hint">Go on. Try the other one. 😂</div></div>`);initNoButton()}
function initNoButton(){const b=document.getElementById('noBtn');if(!b)return;const run=(e)=>escapeNo(e);b.addEventListener('pointerenter',run);b.addEventListener('pointerdown',run);b.addEventListener('touchstart',run,{passive:false});b.addEventListener('focus',run);b.addEventListener('keydown',e=>{if(['Enter',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))run(e)});b.addEventListener('click',run);}
function escapeNo(e){if(e){e.preventDefault?.();e.stopPropagation?.()}const b=document.getElementById('noBtn');if(!b)return false;const pad=18,bw=b.offsetWidth||100,bh=b.offsetHeight||48,maxX=Math.max(pad,innerWidth-bw-pad),maxY=Math.max(90,innerHeight-bh-pad);let x=pad+Math.random()*(maxX-pad),y=80+Math.random()*(Math.max(1,maxY-80));const yes=document.querySelector('.yes')?.getBoundingClientRect();if(yes){for(let t=0;t<80;t++){const overlap=!(x+bw+28<yes.left||x-28>yes.right||y+bh+28<yes.top||y-28>yes.bottom);if(!overlap)break;x=pad+Math.random()*(maxX-pad);y=80+Math.random()*(Math.max(1,maxY-80))}}b.style.position='fixed';b.style.left=`${x}px`;b.style.top=`${y}px`;b.style.zIndex='120';b.style.transform=`rotate(${Math.random()*18-9}deg) scale(${.94+Math.random()*.08})`;const msgs=['Nice try. 😂','That button has other plans.','Nope. I’m protecting the YES button. ❤️','You really thought that would work? 😌','The NO button has left the conversation.'];const hint=document.getElementById('noHint');if(hint)hint.textContent=msgs[Math.floor(Math.random()*msgs.length)];return false}
function celebrate(){state.stage=7;save();setChapter('07 October · Naina day');burst();screen(`<div class="celebrate"><div class="confetti-word">✦ &nbsp; ✧ &nbsp; ✦</div><span class="eyebrow">07 October</span><h1>Happy Birthday,<br><em>Naina.</em></h1><p class="lead">Some people deserve a message.<br>You deserved a whole little world.</p><div class="letter"><p>Naina,</p><p>I could have sent you a simple “Happy Birthday” and called it a day. But somehow, that felt too ordinary for you.</p><p>You’re the girl who loves dogs a little too much, dreams about seeing new places, laughs at the little things, and is quietly building a future for herself. I hope the version of you that becomes a brilliant Business Analyst never forgets the cute, curious girl who started the journey.</p><p>I hope this year gives you new places to wander, good people to come home to, reasons to laugh until your cheeks hurt, and the courage to keep choosing the life you want.</p><p>And selfishly… I hope some of those adventures have me somewhere in the frame.</p><p>Happy Birthday, you ridiculously cute human. ❤️</p><p>— someone who thought a normal birthday wish was not enough</p></div><button class="primary" onclick="finalSurprise()">There’s one more thing <b>↗</b></button></div>`)}
function finalSurprise(){const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="surprise"><button class="close photo-close" aria-label="Close surprise" onclick="this.closest('.overlay').remove()">×</button><div class="surprise-media"><img src="assets/memory-8.jpg" alt="Naina's story" onerror="this.style.display='none';this.parentElement.classList.add('image-missing')"><span>07 · 10 · 1994</span></div><div class="surprise-copy"><span class="eyebrow">the last little secret</span><h2>For all the places<br><em>we haven’t been yet.</em></h2><p>Maybe someday we’ll look back and realise the best part was never the destination.</p><strong>It was having someone worth going with.</strong><div class="tiny-heart">♡</div></div></div>`;document.body.appendChild(o)}
function burst(){for(let i=0;i<110;i++)setTimeout(()=>{const c=document.createElement('span');c.className='confetti';c.textContent=Math.random()>.35?'♥':'✦';c.style.left=Math.random()*100+'vw';c.style.setProperty('--dx',(Math.random()*220-110)+'px');c.style.animationDelay=Math.random()*.5+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),4000)},i*18)}
function ambient(){const a=document.getElementById('ambient');for(let i=0;i<18;i++){const s=document.createElement('span');s.textContent=Math.random()>.5?'♡':'·';s.style.left=Math.random()*100+'vw';s.style.fontSize=(12+Math.random()*22)+'px';s.style.animationDelay=(-Math.random()*12)+'s';s.style.animationDuration=(8+Math.random()*10)+'s';a.appendChild(s)}}
document.getElementById('musicBtn').onclick=()=>{if(music.paused)playSong();else{music.pause();document.getElementById('musicBtn').classList.remove('playing');document.querySelector('#musicBtn span').textContent='Music'}};ambient();home();
